version: "3.8"
services:
  postgres_satriaagung:
    image: postgres:15
    container_name: postgres_satriaagung
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: db_satriaagung
    ports:
      - "22010:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin_satriaagung:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_satriaagung
    restart: always
    env_file:
      - .env
    ports:
      - "44010:80"
    depends_on:
      - postgres_satriaagung

volumes:
  postgres_data:
